import type { SimpleIcon } from 'simple-icons'
import {
  siApache,
  siCodeigniter,
  siDocker,
  siDotnet,
  siGithubactions,
  siGitlab,
  siGo,
  siMongodb,
  siNextdotjs,
  siNodedotjs,
  siNuxt,
  siPhp,
  siPodman,
  siPostgresql,
  siPrisma,
  siReact,
  siSphinx,
  siSwagger,
  siTailwindcss,
  siTraefikproxy,
  siTurborepo,
  siTypescript,
  siVitest,
  siVuedotjs,
} from 'simple-icons'

// Registre nom de techno → logo (Simple Icons, embarqués dans le bundle, aucun
// appel réseau). Point d'extension unique : une techno absente d'ici s'affiche
// simplement avec son nom (voir TechBadge). Ajouter un logo = une ligne.
export const techIcons: Record<string, SimpleIcon> = {
  'Nuxt 4': siNuxt,
  'Vue 3': siVuedotjs,
  'Nuxt / Vue 3': siNuxt,
  'TypeScript': siTypescript,
  'Tailwind': siTailwindcss,
  'PostgreSQL': siPostgresql,
  'Prisma': siPrisma,
  'Vitest': siVitest,
  'GitHub Actions': siGithubactions,
  '.NET 10': siDotnet,
  'ASP.NET Core': siDotnet,
  'Next.js 15': siNextdotjs,
  'React': siReact,
  'Docker': siDocker,
  'Traefik': siTraefikproxy,
  'PHP': siPhp,
  'CodeIgniter 4': siCodeigniter,
  'Podman': siPodman,
  'Sphinx': siSphinx,
  'Node.js': siNodedotjs,
  'MongoDB': siMongodb,
  'CI/CD GitLab': siGitlab,
  'Swagger': siSwagger,
  'Turbo': siTurborepo,
  'Apache': siApache,
  'Go': siGo,
}
